version: '3.1'
services:
  ##authconnect:
    ##build:
    ##  context: .
    ##  dockerfile: Dockerfile
   ## restart: always
   ## container_name: authconnect
    ##volumes:
    ##  - ./authenticator_api:/usr/app
   ## ports:
   ##   - '4000:4000'
    

  postgres:
    image: postgres:latest
    container_name: authconnect_postgres
    environment:
      - POSTGRES_USER=authconnect
      - POSTGRES_PASSWORD=connect
      - POSTGRES_DB=authconnect
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data

volumes:
  postgres_data:
